Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Escola_Segura.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rental4You.Data;

namespace Rental4You.Models
{
	public class CategoriasController : Controller
	{
		private readonly ApplicationDbContext _context;

		public CategoriasController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: Categorias
		[Authorize(Roles = "Admin, Gestor, Funcionario")]
		public async Task<IActionResult> Index()
		{
			return _context.Categorias != null ?
						View(await _context.Categorias.Include(c => c.Veiculos).ToListAsync()) :
						Problem("Entity set 'ApplicationDbContext.Categorias'  is null.");
		}

		// GET: Categorias/Details/5
		[Authorize(Roles = "Admin, Gestor, Funcionario")]
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Categorias == null)
			{
				return NotFound();
			}

			var categoria = await _context.Categorias
				.FirstOrDefaultAsync(m => m.Id == id);
			if (categoria == null)
			{
				return NotFound();
			}

			return View(categoria);
		}

		// GET: Categorias/Create
		[Authorize(Roles = "Admin")]
		public IActionResult Create()
		{
			return View();
		}

		// POST: Categorias/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Create([Bind("Id,Nome")] Categoria categoria)
		{
			ModelState.Remove(nameof(categoria.Veiculos));
			if (ModelState.IsValid)
			{
				_context.Add(categoria);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(categoria);
		}

		// GET: Categorias/Edit/5
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Categorias == null)
			{
				return NotFound();
			}

			var categoria = await _context.Categorias.FindAsync(id);
			if (categoria == null)
			{
				return NotFound();
			}
			return View(categoria);
		}

		// POST: Categorias/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Categoria categoria)
		{
			if (id != categoria.Id)
			{
				return NotFound();
			}
			ModelState.Remove(nameof(categoria.Veiculos));
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(categoria);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!CategoriaExists(categoria.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(categoria);
		}

		// GET: Categorias/Delete/5
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Categorias == null)
			{
				return NotFound();
			}

			var categoria = await _context.Categorias
				.Include(m => m.Veiculos)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (categoria == null)
			{
				return NotFound();
			}
			if (categoria.Veiculos != null && categoria.Veiculos.Count() != 0)
			{
				return BadRequest();
			}

			return View(categoria);
		}

		// POST: Categorias/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Categorias == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Categorias'  is null.");
			}
			var categoria = await _context.Categorias.FindAsync(id);
			if(categoria == null)
            {
				return NotFound();
            }

            if (categoria.Veiculos != null && categoria.Veiculos.Count() != 0)
            {
                return BadRequest();
            }
            if (categoria != null)
            {
                _context.Categorias.Remove(categoria);
            }

            await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool CategoriaExists(int id)
		{
			return (_context.Categorias?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Escola_Segura.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rental4You.Data;
using Rental4You.Models;
using Rental4You.ViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Rental4You.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        public UsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
        }

		// GET: /<controller>/
		[Authorize(Roles = "Admin, Gestor")]
		public async Task<IActionResult> Index()
        {
            List<UserRolesViewModel> viewModel = new List<UserRolesViewModel>();
            List<ApplicationUser> users = null;
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            ViewBag.userId = applicationUser.Id;
            if (User.IsInRole("Admin"))
            {
                users = _userManager.Users.ToList();


            }
            else if (User.IsInRole("Gestor"))
            {
                users = _userManager.Users
                    .Where(user => user.EmpresaId == applicationUser.EmpresaId)
                    .Include(user => user.Registos)
                    .ToList();
            }
            users?.ForEach(user =>
            {
                viewModel.Add(UserRolesViewModel.mapUserToViewModel(user, _userManager.GetRolesAsync(user).GetAwaiter().GetResult()));
            });

            return View(viewModel);
        }

        [Authorize(Roles = "Gestor")]
        public async Task<IActionResult> Create()
        {
            List<IdentityRole> roles = _roleManager.Roles.Where(r => r.Name == Roles.Gestor.ToString() || r.Name == Roles.Funcionario.ToString()).ToList();
            ViewData["Roles"] = new SelectList(roles, "Name", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Gestor")]
        public async Task<IActionResult> Create([Bind("Id,PrimeiroNome,UltimoNome,DataNascimento,Email,NIF,EmpresaId")] ApplicationUser user, string role)
        {
            List<IdentityRole> roles;
            roles = _roleManager.Roles.Where(r => r.Name == Roles.Gestor.ToString() || r.Name == Roles.Funcionario.ToString()).ToList();
            ViewData["Roles"] = new SelectList(roles, "Name", "Name");

            if (user.DataNascimento >= DateTime.Today)
            {
                ModelState.AddModelError("DataNascimento", "A data de nascimento não pode ser igual ou superior à data atual");

                return View(user);
            }
            user.Active = true;
            ModelState.Remove(nameof(user.Empresa));
            ModelState.Remove(nameof(user.Reservas));
            ModelState.Remove(nameof(user.Registos));

            if (role == null || (role != Roles.Funcionario.ToString() && role != Roles.Gestor.ToString()))
            {
                return View(user);
            }
            ApplicationUser gestor = await _userManager.GetUserAsync(User);
            user.EmpresaId = gestor.EmpresaId;
            user.EmailConfirmed = true;
            user.DataRegisto = DateTime.Now;


            if (ModelState.IsValid)
            {
                user.UserName = user.Email;
                IdentityResult result = null;
                if(role == Roles.Funcionario.ToString())
                {
                    result = await _userManager.CreateAsync(user, "Funcionario123!");
                }
                else if(role == Roles.Gestor.ToString())
                {
                    result = await _userManager.CreateAsync(user, "Gestor123!");
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Nao foi possivel criar o utilizador");

                    return View(user);
                }
                result = await _userManager.AddToRoleAsync(user, role);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Nao foi possivel atribuir o role ao utilizador");
                    return View(user);
                }
                return RedirectToAction(nameof(Index));
            }

            return View(user);
        }


		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(string UserId)
        {
            if (String.IsNullOrEmpty(UserId))
            {
                return RedirectToAction("Index");

            }
            var user = await _userManager.FindByIdAsync(UserId);
            if (user == null)
            {
                return RedirectToAction("Index");
            }

            var roles = _roleManager.Roles.ToList();
            List<string> rolesUser = (List<string>)_userManager.GetRolesAsync(user).GetAwaiter().GetResult();
            UserDetailsViewModel userDetails = UserDetailsViewModel.mapToViewModel(user);

            userDetails.roles = new List<RolesViewModel>();

            foreach (var role in roles)
            {
                RolesViewModel rolesViewModel = new RolesViewModel();
                rolesViewModel.RoleId = role.Id;
                rolesViewModel.RoleName = role.Name;
                rolesViewModel.Selected = rolesUser.Contains(role.Name);
                userDetails.roles.Add(rolesViewModel);
            }

            return View(userDetails);
        }




        [HttpPost]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(UserDetailsViewModel userDetails, string userId)
        {
            if (String.IsNullOrEmpty(userId))
            {
                return RedirectToAction("Index");

            }

            if(userDetails.DataNascimento >= DateTime.Today)
            {
                ModelState.AddModelError("DataNascimento", "A data de nascimento não pode ser igual ou superior à data atual");
            }

            ModelState.Remove(nameof(userDetails.roles));
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            user.UserName = user.Email;
            if (!ModelState.IsValid)
            {
                userDetails.Id = user.Id;
                return View(userDetails);
            }

            user.DataNascimento = userDetails.DataNascimento;
            user.Active = userDetails.Active;
            user.NIF = userDetails.NIF;
            user.PrimeiroNome = userDetails.PrimeiroNome;
            user.UltimoNome = userDetails.UltimoNome;

            _context.Update(user);
            await _context.SaveChangesAsync();

            List<string> rolesUser = (List<string>)_userManager.GetRolesAsync(user).GetAwaiter().GetResult();
            var result = await _userManager.RemoveFromRolesAsync(user, rolesUser);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Não é possivel remover uma role existente");
                return View(userDetails);
            }
            result = await _userManager.AddToRolesAsync(user, userDetails.roles.Where(m => m.Selected).Select(m => m.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Não é possivel adionar uma role existente");
                return View(userDetails);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles= "Admin, Gestor")]
        public async Task<IActionResult> ChangeStatus(string userId, [Bind("Active")] Boolean Active)
        {
            if(userId == null)
            {
                return NotFound();
            }
            ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
            if(user == null)
            {
                return NotFound();
            }
			ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
			if (applicationUser == null || applicationUser.Id == userId)
			{
				return BadRequest();
			}
			user.Active = Active;
            _context.Update(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

		[Authorize(Roles = "Gestor")]
		public async Task<IActionResult> Delete(string userId)
        {
            if (userId == null || _context.Users == null)
            {
                return NotFound();
            }

			ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            if(applicationUser == null || applicationUser.Id == userId)
            {
                return BadRequest();
            }

			var user = await _context.Users
                .Include(u => u.Registos)
                .FirstOrDefaultAsync(m => m.Id == userId);
            if (user == null)
            {
                return NotFound();
            }
            if (user.Registos != null && user.Registos.Count() != 0)
            {
                ModelState.AddModelError("", "Não é possivel eliminar um utilizador com reservas");
                return BadRequest();
            }
            return View(user);
        }

        // POST: Reservas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Gestor")]
		public async Task<IActionResult> DeleteConfirmed(string Id)
        {
            if (_context.Users == null)
            {

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Rental4You</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Rental4You.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rental4You</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						@if (User.IsInRole("Admin"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Empresas" asp-action="Index">
									Empresas
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Veiculos" asp-action="Index">
									Veiculos
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">
									Categorias
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Users" asp-action="Index">
									Utilizadores
								</a>
							</li>
						}
						else if (User.IsInRole("Gestor"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Reservas" asp-action="Index">
									Reservas
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Veiculos" asp-action="Index">
									Frota
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">
									Categorias
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Users" asp-action="Index">
									Utilizadores
								</a>
							</li>
						}
						else if (User.IsInRole("Funcionario"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Reservas" asp-action="Index">
									Reservas
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Veiculos" asp-action="Index">
									Frota
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">
									Categorias
								</a>
							</li>
						}
						else if (User.IsInRole("Cliente"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Reservas" asp-action="Index">
									Reservas
								</a>
							</li>

						}
						else
						{

						}
					</ul>

					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - Rental4You - <a asp-area="" asp-controller="Home" asp-action="Privacy">Realizado por:</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutHomeClient.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Rental4You</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Rental4You.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rental4You</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						@if (User.IsInRole("Admin"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Empresas" asp-action="Index">
									Empresas
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Veiculos" asp-action="Index">
									Veiculos
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">
									Categorias
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Users" asp-action="Index">
									Utilizadores
								</a>
							</li>
						}
						else if (User.IsInRole("Gestor"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Reservas" asp-action="Index">
									Reservas
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Veiculos" asp-action="Index">
									Frota
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">
									Categorias
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Users" asp-action="Index">
									Utilizadores
								</a>
							</li>
						}
						else if (User.IsInRole("Funcionario"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Reservas" asp-action="Index">
									Reservas
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Veiculos" asp-action="Index">
									Frota
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">
									Categorias
								</a>
							</li>
						}
						else if (User.IsInRole("Cliente"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Reservas" asp-action="Index">
									Reservas
								</a>
							</li>

						}
						else
						{

						}
					</ul>

					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container-fluid">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - Rental4You - <a asp-area="" asp-controller="Home" asp-action="Privacy">Realizado por:</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>