Models/Reserva.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Rental4You.Models
{
    public enum StatusReserva
    {
        approved, delivered, pending, provided, rejected

    }
    public class Reserva
    {
        public int ReservaId { get; set; }
        public bool Concluido { get; set; }
        public DateTime DataLevantamento { get; set; }
        public DateTime DataEntrega { get; set; }
        public double CustoTotal { get; set; }
        public int VeiculoId { get; set; }
        public Veiculo Veiculo { get; set; }

        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        public int? LevantamentoId { get; set; }
        public Registo? Levantamento { get; set; }
        
        public int? EntregaId { get; set; }
        public Registo? Entrega { get; set; }

        public Avaliacao? Avaliacao { get; set; }

        [DefaultValue(StatusReserva.pending)]
        public StatusReserva Estado {get; set;}
        public static string translate(StatusReserva? status){
            if(status == null) return "";
            switch(status){
                case StatusReserva.pending :
                    return "Pendente";
                case StatusReserva.approved:
                    return "Aprovado";
                case StatusReserva.delivered:
                    return "Concluida";
                case StatusReserva.provided:
                    return "Levantada"; 
                case StatusReserva.rejected:
                    return "Rejeitado";
                default: 
                    return "";  
            }
        }
        [DataType(DataType.Date)]
		public DateTime DataReserva { get; set; }
	}
}

Controllers/AvaliacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rental4You.Data;

namespace Rental4You.Models
{
    public class AvaliacoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AvaliacoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Avaliacoes
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Avaliacoes.Include(a => a.Empresa);
            return View(await applicationDbContext.ToListAsync());
        }


        // POST: Avaliacoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ReservaId,EmpresaId,Nota")] Avaliacao avaliacao)
        {
            ModelState.Remove(nameof(avaliacao.Empresa));
            ModelState.Remove(nameof(avaliacao.Reserva));
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(avaliacao);
                    await _context.SaveChangesAsync();
                    var media = _context.Avaliacoes.Where(a => a.EmpresaId == avaliacao.EmpresaId).Select(a => a.Nota).Average();
                    var empresa = _context.Empresas.FirstOrDefault(e => e.Id == avaliacao.EmpresaId);
                    if (empresa == null)
                    {
						return NotFound();
					}
                    empresa.MediaAvaliacao = media;
                
                    _context.Update(empresa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
					return BadRequest();
				}
                return RedirectToAction("Index","Reservas");
            }
            
                ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Id", avaliacao.EmpresaId);
            return RedirectToAction("Details", "Reservas", new { id = avaliacao.ReservaId});
        }

        // POST: Avaliacoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(int id, [Bind("Id,EmpresaId")] Avaliacao avaliacao)
        {
            if (id != avaliacao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(avaliacao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AvaliacaoExists(avaliacao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Id", avaliacao.EmpresaId);
            return View(avaliacao);
        }

        private bool AvaliacaoExists(int id)
        {
            return (_context.Avaliacoes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/RegistosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Escola_Segura.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rental4You.Data;

namespace Rental4You.Models
{
    public class RegistosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RegistosController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        //// GET: Registos
        //[Authorize(Roles = "Admin,Gestor,Funcionario,Cliente")]
        //public async Task<IActionResult> Index(RegistoType? tipo)
        //{
        //    ApplicationUser user = await _userManager.GetUserAsync(User);
        //    List<Registo> registos;
        //    IQueryable<Registo> reg;
        //    if (User.IsInRole(Roles.Admin.ToString()))
        //    {
        //        reg = _context.Registos;
        //    }else if (User.IsInRole(Roles.Gestor.ToString()) || User.IsInRole(Roles.Funcionario.ToString()))
        //    {
        //        reg = _context.Registos.Where(r => r.Funcionario.Id == user.Id);   
        //    }else{
        //        reg = _context.Registos.Include(r => r.Reserva)
        //        .Where(r => r.Reserva.ApplicationUserId == user.Id);
        //    }

        //    if(tipo != null)
        //    {
        //        reg.Where(r => r.Tipo == tipo);
        //    }
        //    registos = reg.ToList();
        //    return View(registos);                         
        //}

        // GET: Registos/Details/5
        [Authorize(Roles = "Admin,Gestor,Funcionario,Cliente")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Registos == null)
            {
                return NotFound();
            }

            var registo = await _context.Registos
                .Include(m => m.Funcionario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registo == null)
            {
                return NotFound();
            }
            try
            {
                string CoursePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Ficheiros/Registos/" + id.ToString());
                var files = from file in Directory.EnumerateFiles(CoursePath) select string.Format("/Ficheiros/{0}/{1}", id, Path.GetFileName(file));
                ViewData["NFich"] = files.Count();
                ViewData["Ficheiro"] = files;

            }
            catch (Exception ex)
            {

            }

            return View(registo);
        }

        // GET: Registos/Create
        [Authorize(Roles = "Gestor,Funcionario")]
        public async Task<IActionResult> CreateAsync(RegistoType tipo, int idReserva)
        {
            var r = new Registo();
            r.Tipo = tipo;
            Reserva? reserva = _context.Reservas.Include(r => r.Levantamento).Include(r => r.Entrega).FirstOrDefault( r => r.ReservaId == idReserva);
            if(reserva == null)
            {
                return NotFound();
            }
            if (tipo == RegistoType.LEVANTAMENTO && reserva.Levantamento != null)
            {
                return NotFound();
            }
            else if (tipo == RegistoType.LEVANTAMENTO && reserva.Entrega != null)
            {
                return NotFound();
            }
            else if (tipo == RegistoType.ENTREGA && reserva.Levantamento == null)
            {
                return NotFound();
            }
            else if (tipo == RegistoType.ENTREGA && reserva.Entrega != null)
            {
                return NotFound();
            }
            
            r.Data = DateTime.Now;
            r.ReservaId = idReserva;
            return View(r);
        }

        // POST: Registos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Gestor,Funcionario")]
        public async Task<IActionResult> Create([Bind("Id,Data,Kms,Danos,Tipo,ReservaId,Observacoes")] Registo registo, [FromForm] List<IFormFile> ficheiros)
        {

            ModelState.Remove(nameof(registo.Reserva));
            ModelState.Remove(nameof(registo.Funcionario));
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if(user == null)
            {
                return Unauthorized();
            }

            Reserva? reserva = _context.Reservas.Include(r => r.Veiculo).FirstOrDefault(r => r.ReservaId == registo.ReservaId);
            if(reserva == null)
            {
                return View(registo);
            }

            if(registo.Tipo == RegistoType.LEVANTAMENTO && reserva.Estado == StatusReserva.approved)
            {
                reserva.Estado = StatusReserva.provided;
                reserva.Levantamento = registo;
            }else if (registo.Tipo == RegistoType.ENTREGA && reserva.Estado == StatusReserva.provided)
            {
                reserva.Estado = StatusReserva.delivered;
                reserva.Entrega = registo;
                reserva.Concluido = true;
            }
            else
            {
                return View(registo);
            }
            
            registo.Funcionario = user;



            if (ModelState.IsValid)
            {
                try { 
                    _context.Add(registo);
                    _context.Update(reserva);
                    _context.Update(reserva.Veiculo);
                    await _context.SaveChangesAsync();

                    string CoursePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Ficheiros/Registos/" + registo.Id.ToString());

                    if (!Directory.Exists(CoursePath))
                    {
                        Directory.CreateDirectory(CoursePath);
                    }

                    foreach (var formFile in ficheiros)
                    {
                        if (formFile.Length > 0)
                        {
                            var filePath = Path.Combine(CoursePath, Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName));
                            while (System.IO.File.Exists(filePath))
                            {
                                filePath = Path.Combine(CoursePath, Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName));
                            }
                            using (var stream = System.IO.File.Create(filePath))
                            {
                                await formFile.CopyToAsync(stream);
                            }
                        }
                    }

                }
                catch(Exception e)
                {

                }

                return RedirectToAction("Index", "Reservas");
            }
            return View(registo);
        }

        //// GET: Registos/Edit/5
        //[Authorize(Roles = "Gestor,Funcionario")]
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null || _context.Registos == null)
        //    {
        //        return NotFound();
        //    }

        //    var registo = await _context.Registos.FindAsync(id);
        //    if (registo == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(registo);
        //}

        // POST: Registos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Roles = "Gestor,Funcionario")]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Data,Kms,Danos,Observacoes")] Registo registo, [FromForm] List<IFormFile> ficheiros)
        //{
        //    if (id != registo.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(registo);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!RegistoExists(registo.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction("Index", "Reservas");
        //    }
        //    return View(registo);
        //}

        //private bool RegistoExists(int id)
        //{
        //  return (_context.Registos?.Any(e => e.Id == id)).GetValueOrDefault();
        //}
    }
}

Views/Reservas/Create.cshtml
@model Rental4You.Models.Reserva

@{
    ViewData["Title"] = "Create";
}

<h1>Nova</h1>

<h4>Reserva</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DataLevantamento" class="control-label"></label>
                <input asp-for="DataLevantamento" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="DataEntrega" class="control-label"></label>
                <input asp-for="DataEntrega" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Veiculo.CustoDia" class="control-label"></label>
                <input asp-for="Veiculo.CustoDia" disabled class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CustoTotal" class="control-label"></label>
                <input asp-for="CustoTotal" disabled class="form-control" />
            </div>
            <div class="form-group">
                <button type="submit" asp-action="Create" class="btn btn-primary" >Reservar</button>
            </div>
            <div class="form-group">
                <button type="submit" asp-action="NovaReserva" class="btn btn-primary">Calcular</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-warning btn-sm">Voltar a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reservas/Delete.cshtml
@model Rental4You.Models.Reserva

@{
    ViewData["Title"] = "Delete";
}

<h1>Remover</h1>

<h3>Tem a certeza que quer remover esta reserva?</h3>
<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Concluido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Concluido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Veiculo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Veiculo.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReservaId" />
        <input type="submit" value="Remover" class="btn btn-danger btn-sm" /> |
        <a asp-action="Index" class="btn btn-secondary btn-sm">Voltar a Lista</a>
    </form>
</div>

Views/Reservas/Details.cshtml
@model Rental4You.Models.Reserva

@{
    ViewData["Title"] = "Details";
}

<h1>Reserva</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Marca do Veiculo
        </dt>
        <dd class="col-sm-10">
            @Model.Veiculo.Marca
        </dd>
        <dt class="col-sm-2">
            Modelo do Veiculo
        </dt>
        <dd class="col-sm-10">
            @Model.Veiculo.Modelo
        </dd>
        <dt class="col-sm-2">
            Matricula do Veiculo
        </dt>
        <dd class="col-sm-10">
            @Model.Veiculo.Matricula
        </dd>
        <dt class="col-sm-2">
            Estado da Reserva:
        </dt>
        <dd class="col-sm-10">
            @Reserva.translate(Model.Estado)
        </dd>
        <dt class="col-sm-2">
            Data de Levantamento:
        </dt>
        <dd class="col-sm-10">
            @Model.DataLevantamento
        </dd>
        <dt class="col-sm-2">
            Data de Entrega:
        </dt>
        <dd class="col-sm-10">
            @Model.DataEntrega
        </dd>
        <dt class="col-sm-2">
            Concluido
        </dt>
        <dd class="col-sm-10">
            <input asp-for="Concluido" readonly="readonly" disabled />
        </dd>


        @if (User.IsInRole("Cliente") && Model != null) //Se for cliente e se o id for ele
        {
            <form asp-action="Create" asp-controller="Avaliacoes">
                <input type="hidden" name="ReservaId" value="@Model.ReservaId" />
                <input type="hidden" name="EmpresaId" value="@Model.Veiculo.EmpresaId" />

                @if (Model.EntregaId == null)
                {
                <dd class="col-sm-10">Só pode submeter uma avalição depois da entrega do Veiculo</dd>

            }
            else if (Model.Avaliacao == null)
            {
                <dt class="col-sm-2">
                    Nota (1 a 10)
                </dt>

                <input name="Nota" asp-for="Avaliacao.Nota" />
                <span asp-validation-for="Avaliacao.Nota" class="text-danger"></span>
                <button type="submit" class="btn btn-primary">Submeter Avaliação</button>
            }

            else
            {
                <dt class="col-sm-2">
                    Nota
                </dt>
                <dd class="col-sm-10">@Model.Avaliacao.Nota</dd>

            }

                </form>
            }
            else
            {
                @if (Model.Avaliacao != null)
                {
                    <div>
                        <label asp-for="Avaliacao.Nota"></label>
                        <input asp-for="Avaliacao.Nota" readonly="readonly" />
                    </div>
 }
                else
                {
                    <div>Esta reserva não possui Avaliação</div>
                }
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-warning btn-sm">Voltar a Lista</a>
    @if(Model != null && Model.LevantamentoId != null){
        <a asp-action="Details" asp-controller="Registos" asp-route-id="@Model.LevantamentoId" class="btn btn-warning btn-sm">Ver Levantamento</a>
    }
    @if(Model != null && Model.EntregaId != null){
        <a asp-action="Details" asp-controller="Registos" asp-route-id="@Model.EntregaId" class="btn btn-warning btn-sm">Ver Entrega</a>
    }
</div>



Views/Reservas/Edit.cshtml
@model Rental4You.Models.Reserva

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Reserva</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReservaId" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Concluido" /> @Html.DisplayNameFor(model => model.Concluido)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="VeiculoId" class="control-label"></label>
                <select asp-for="VeiculoId" class="form-control" asp-items="ViewBag.VeiculoId"></select>
                <span asp-validation-for="VeiculoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserId" class="control-label"></label>
                <select asp-for="ApplicationUserId" class="form-control" asp-items="ViewBag.ApplicationUserId"></select>
                <span asp-validation-for="ApplicationUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-warning btn-sm">Voltar a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reservas/Index.cshtml
@using Rental4You.Models
@model Rental4You.ViewModel.ReservasSearchViewModel

@{
	ViewData["Title"] = "Index";
}

<h1>Reservas</h1>

<form asp-action="Index" method="get">
	<div class="row">
		@if (User.IsInRole("Cliente"))
		{
			<div class="col-2 form-group mb-2">
				<label>Nome da Empresa</label>
				<input type="text" asp-for="NomeEmpresa" name="NomeEmpresa" class="field" />
			</div>
		}
		else
		{
			<div class="col-2 form-group mb-2">
				<label>Nome do Cliente</label>
				<input type="text" asp-for="NomeCliente" name="NomeCliente" class="field" />
			</div>
		}
		<div class="col-2 form-group mb-2">
			<label>Veiculo</label>
			<input type="text" asp-for="Veiculo" name="Veiculo" class="field" />
		</div>
		<div class="col-2 mb-2">
			<label>Data de Levantamento</label>
			<input asp-for="DataLevantamento" name="DataLevantamento" asp-format="{0:yyyy-MM-ddTHH:mm}" class="field" />
		</div>
		<div class="col-2 mb-2">
			<label>Data de Entrega</label>
			<input asp-for="DataEntrega" name="DataEntrega" asp-format="{0:yyyy-MM-ddTHH:mm}" class="field" />
		</div>
	</div>


	<div class="row">
		<div class="col-2 form-group mb-2">
			<label class="col-12">Estado:</label>
			<select name="Estado" asp-items=@ViewBag.Estado class="form-group mb-2 field"></select>
		</div>
		<div class="col-2 form-group mb-2">
			<label class="col-12">Categorias:</label>
			<select name="Categoria" asp-items=@ViewBag.Categorias class="form-group field"></select>
		</div>
		<div class="col-2 form-group mb-2">
			<label>Ordenar por:</label>
			<select name="order" asp-items=@ViewBag.Order class="form-group field"></select>
		</div>
	</div>
	<div class="row">
		<div class="col-2 form-group mb-2">
			<div type="button" id="btnreset" class="btn btn-success field">Limpar Filtros</div>
		</div>
		<div class="col-2 form-group mb-2">
			<button type="submit" class="btn btn-success field">Pesquisar</button>
		</div>
	</div>
</form>



<table class="table">
	<thead>
		<tr class="bg-info bg-opacity-25">
			<th>
				Veiculo
			</th>
			@if (User.IsInRole("Cliente"))
			{
				<th>
					Empresa
				</th>
			}
			else
			{
				<th>
					Cliente
				</th>
			}
			<th>
				Avaliação
			</th>
			<th>
				Data de Levantamento
			</th>
			<th>
				Data de Entrega
			</th>
			<th>
				Estado
			</th>
			<th>
				Concluido
			</th>
			<th>Acções</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model.reservas)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Veiculo.Nome)
				</td>
				@if (User.IsInRole("Cliente"))
				{
					<td>
						@Html.DisplayFor(modelItem => item.Veiculo.Empresa.Nome)
					</td>
				}
				@if (!User.IsInRole("Cliente"))
				{
					<td>
						@item.ApplicationUser.PrimeiroNome @item.ApplicationUser.UltimoNome
					</td>
				}
				@if (item.Avaliacao == null)
				{
					<td>--</td>

				}
				else
				{
					<td>@item.Avaliacao.Nota/10</td>
				}
				<td>
					@Html.DisplayFor(modelItem => item.DataLevantamento)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.DataEntrega)
				</td>
				<td>
					@Reserva.translate(item.Estado)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Concluido)
				</td>
				<td>
					<div class="row">
						<div class="col-3">
							<a asp-action="Details" asp-route-id="@item.ReservaId" class="btn btn-success btn-sm">Detalhes</a>
						</div>
						@if (!User.IsInRole("Cliente"))
						{
							@if (item.Estado == StatusReserva.pending)
							{
								<div class="col-3" style="margin-left: 15px;">
									<form asp-action="ChangeStatus" asp-route-id="@item.ReservaId" method="post">
										<input type="hidden" name="newStatus" value="@StatusReserva.approved" />
										<button type="submit" class="btn btn-success btn-sm">Aprovar</button>
									</form>
								</div>
								<div class="col-3" style="margin-left: 15px;">
									<form asp-action="ChangeStatus" asp-route-id="@item.ReservaId" method="post">
										<input type="hidden" name="newStatus" value="@StatusReserva.rejected" />
										<button type="submit" class="btn btn-danger btn-sm">Rejeitar</button>
									</form>
								</div>
							}
							else if (item.Estado == StatusReserva.approved)
							{
								<div class="col-3" style="margin-left: 15px;">
									@if (item.Levantamento == null)
									{
										<a asp-action="Create" asp-controller="Registos" asp-route-idReserva="@item.ReservaId"
						   asp-route-tipo="@RegistoType.LEVANTAMENTO" class="btn btn-warning btn-sm">Levantamento</a>
									}
								</div>
							}
							else if (item.Estado == StatusReserva.provided)
							{
								<div class="col-3" style="margin-left: 15px;">
									@if (item.Entrega == null)
									{
										<a asp-action="Create" asp-controller="Registos" asp-route-idReserva="@item.ReservaId"
						   asp-route-tipo="@RegistoType.ENTREGA" class="btn btn-warning btn-sm">Entrega</a>
									}
								</div>
							}
						}
					</div>
				</td>
			</tr>
		}
	</tbody>
</table>


<script>

	document.getElementById('btnreset').addEventListener('click', function (event) {
		var fields = document.getElementsByClassName('field')
		for (let f of fields) {
			f.value = ""
		}
	});

</script>

Views/Reservas/NovaReserva.cshtml
@model Rental4You.Models.Reserva

@{
    ViewData["Title"] = "Create";
}

<h1>Confirmação de Reserva</h1>


<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <input type="hidden" asp-for="VeiculoId"/>
            <div class="form-group mb-3">
                <label class="control-label">Marca do Veiculo</label>
                <input type="text" value = "@ViewBag.Veiculo.Marca" readonly="readonly" placeholder="Marca" class="form-control"/>
            </div>
            <div class="form-group mb-3">
                <label class="control-label">Modelo do Veiculo</label>
                <input type="text" value = "@ViewBag.Veiculo.Modelo" readonly="readonly" placeholder="Modelo" class="form-control"/>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="DataLevantamento" class="control-label"></label>
                <input type="text" asp-for="DataLevantamento" readonly="readonly" placeholder="Localização" class="form-control"/>
            </div>
            <div class="form-group mb-3 ">
                <label asp-for="DataEntrega" class="control-label"></label>
                <input type="text" asp-for="DataEntrega"readonly="readonly" class="form-control" />
            </div>
            <div class="form-group mb-3">
                <label asp-for="Veiculo.CustoDia" class="control-label"></label>
                <input asp-for="Veiculo.CustoDia" readonly="readonly" class="form-control" />
            </div>
            <div class="form-group mb-3">
                <label asp-for="CustoTotal" class="control-label"></label>
                <input asp-for="CustoTotal" readonly="readonly" class="form-control" />
            </div>
            <div class="form-group mb-3">
                <button type="submit" class="btn btn-success">Continuar Reserva</button>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}