Models/Registo.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rental4You.Validations;

namespace Rental4You.Models
{
    public enum RegistoType
    {
        LEVANTAMENTO, ENTREGA
    }

    public class Registo
    {
        public int Id { get; set; }

        [DataType(DataType.DateTime)]
        [BindProperty, DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Data { get; set; }

        [KmsReserva]
        [Range(0, Double.PositiveInfinity, ErrorMessage ="O valor deve ser superior a 0")]
        public double Kms { get; set; }
        public bool Danos { get; set; }
        public ApplicationUser Funcionario { get; set; }

        [StringLength(400, ErrorMessage ="As observações devem ter no maximo 400 caracteres")]
        public string Observacoes { get; set; }
        
        public int ReservaId { get; set; }
        
        public Reserva Reserva { get; set; }

        [DefaultValue(RegistoType.LEVANTAMENTO)]
        public RegistoType Tipo { get; set;}
    }
}

Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rental4You.Data;
using Rental4You.ViewModel;

namespace Rental4You.Models
{
	public class ReservasController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;

		public ReservasController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_userManager = userManager;
		}

		// GET: Reservas
		[Authorize]
		public async Task<IActionResult> Index([Bind("DataLevantamento,DataEntrega,NomeCliente,NomeEmpresa,Veiculo,Estado, Categoria, order")] ReservasSearchViewModel viewModel)
		{
			var EstadoList = GetEstado();
			var CategoriaList = GetCategoria(_context.Categorias.ToList());
			var Order = GetOrder();
			var user = await _userManager.GetUserAsync(User);
			IQueryable<Reserva> reservas = null;
			if (user == null)
			{
				return View();
			}
			if (User.IsInRole("Cliente"))
			{
				reservas = _context.Reservas
					.Include(r => r.ApplicationUser)
					.Include(r => r.Avaliacao)
					.Include(r => r.Veiculo)
					.Include(r => r.Veiculo.Empresa)
					.Where(r => r.ApplicationUserId == user.Id)
					.OrderByDescending(r => r.DataLevantamento)
					.ThenByDescending(r => r.CustoTotal);

			}
			else if (User.IsInRole("Funcionario") || User.IsInRole("Gestor"))
			{
				reservas = _context.Reservas.Include(r => r.ApplicationUser).Include(r => r.Veiculo)
					.Include(r => r.Avaliacao)
					.Where(r => r.Veiculo.EmpresaId == user.EmpresaId);

			}
			else if (User.IsInRole("Admin"))
			{
				reservas = _context.Reservas.Include(r => r.ApplicationUser).Include(r => r.Veiculo)
				   .Include(r => r.Avaliacao);
			}
			else
			{
				return Unauthorized();
			}
			if (reservas != null && viewModel.DataLevantamento != null)
			{
				reservas = reservas.Where(r => r.DataLevantamento >= viewModel.DataLevantamento.Value);
			}

			if (reservas != null && viewModel.DataEntrega != null)
			{
				reservas = reservas.Where(r => r.DataEntrega <= viewModel.DataEntrega.Value);
			}

			if (reservas != null && !String.IsNullOrEmpty(viewModel.NomeCliente))
			{
				reservas = reservas.Where(r => (r.ApplicationUser.PrimeiroNome + " " +
											r.ApplicationUser.UltimoNome).Contains(viewModel.NomeCliente));
			}

			if (reservas != null && !String.IsNullOrEmpty(viewModel.NomeEmpresa))
			{
				reservas = reservas.Where(r => r.Veiculo.Empresa.Nome.Contains(viewModel.NomeEmpresa));
			}

			if (reservas != null && !String.IsNullOrEmpty(viewModel.Veiculo))
			{
				reservas = reservas.Where(r => (r.Veiculo.Nome.Contains(viewModel.Veiculo) || r.Veiculo.Marca.Contains(viewModel.Veiculo) || r.Veiculo.Modelo.Contains(viewModel.Veiculo)));
			}

			if (reservas != null && !String.IsNullOrEmpty(viewModel.Estado))
			{
				reservas = SearchForEstado(viewModel.Estado, reservas);
				EstadoList = SelectListItem(viewModel.Estado, EstadoList);
			}

			if (reservas != null && !String.IsNullOrEmpty(viewModel.Categoria))
			{
				reservas = reservas.Where(r => r.Veiculo.Categoria.Nome.Contains(viewModel.Categoria));
				CategoriaList = SelectListItem(viewModel.Categoria, CategoriaList);
			}
			if (reservas != null && !String.IsNullOrEmpty(viewModel.order))
			{
				reservas = OrderBy(viewModel.order, reservas);
				Order = SelectListItem(viewModel.order, Order);
			}

			ViewData["Categorias"] = CategoriaList;
			ViewData["Estado"] = EstadoList;
			ViewData["Order"] = Order;
			ViewData["DataLevantamento"] = viewModel.DataLevantamento;
			ViewData["DataEntrega"] = viewModel.DataEntrega;
			ViewData["NomeCliente"] = viewModel.NomeCliente;
			ViewData["NomeEmpresa"] = viewModel.NomeEmpresa;
			ViewData["Veiculo"] = viewModel.Veiculo;
			viewModel.reservas = reservas.ToList();
			var model = reservas.ToList();
			return View(viewModel);
		}

		// GET: Reservas/Details/5
		[Authorize(Roles = "Gestor,Funcionario,Cliente")]
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Reservas == null)
			{
				return NotFound();
			}

			var reserva = await _context.Reservas
				.Include(r => r.ApplicationUser)
				.Include(r => r.Veiculo)
				.Include(r => r.Avaliacao)
				.FirstOrDefaultAsync(m => m.ReservaId == id);
			if (reserva == null)
			{
				return NotFound();
			}

			return View(reserva);
		}

		// GET: Reservas/Create
		[Authorize(Roles = "Cliente")]
		public async Task<IActionResult> Create(int? idVeiculo, DateTime datalevantamento, DateTime dataentrega)
		{
			if (idVeiculo == null)
			{
				return NotFound();
			}

			if (datalevantamento > dataentrega)
			{
				return RedirectToAction(nameof(Index));
			}

			ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id");
			ViewData["VeiculoId"] = new SelectList(_context.Veiculos, "Id", "Id");
			var veiculos = _context.Veiculos.Where(v => v.Id == idVeiculo);



			veiculos.Where(veiculo => veiculo.Reservas == null ||
												  veiculo.Reservas.Count() == 0 ||
												  veiculo.Reservas.Where(reserva =>
														//     13-12-2022 < 19-12-2022      &&   20-12-2022 < 24-12-2022  1-1
														(datalevantamento <= reserva.DataLevantamento && reserva.DataEntrega <= dataentrega) ||
														//     18-12-2022 < 19-12-2022      &&   18-12-2022 < 19-12-2022 1-1
														(datalevantamento <= reserva.DataLevantamento && reserva.DataLevantamento <= dataentrega) ||
													   //     19-12-2022 < 20-12-2022      &&   20-12-2022 < 24-12-2022 1-1
													   (datalevantamento <= reserva.DataEntrega && reserva.DataEntrega <= dataentrega) ||
													   //     19-12-2022 11:00 > 19-12-2022 10:00     &&   20-12-2022 11:00 > 20-12-2022 10:00 1-1
													   (datalevantamento >= reserva.DataLevantamento && reserva.DataEntrega >= dataentrega)
													).Count() == 0);
			if (veiculos.Count() == 0)
			{
				return NotFound();
			}

			var veiculo = veiculos.First();

			decimal dias = (dataentrega.Hour - datalevantamento.Hour) / 24;
			ViewData["Valor"] = ((int)Math.Ceiling(dias)) * veiculo.CustoDia;
			ViewBag.veiculo = veiculo;
			Reserva reserva = new Reserva();
			reserva.CustoTotal = ((int)Math.Ceiling(dias)) * veiculo.CustoDia;
			reserva.DataLevantamento = datalevantamento;
			reserva.DataEntrega = dataentrega;

			return View();
		}

		// POST: Reservas/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Cliente")]
		public async Task<IActionResult> Create([Bind("DataLevantamento,DataEntrega,CustoTotal,VeiculoId")] Reserva reserva)
		{

			var veiculo = await _context.Veiculos.FirstOrDefaultAsync(v => v.Id == reserva.VeiculoId);
			if (veiculo == null)
			{
				return NotFound();
			}
			if (reserva.DataEntrega < reserva.DataLevantamento)
			{
				return BadRequest();
			}
			ModelState.Remove(nameof(reserva.Veiculo));
			ModelState.Remove(nameof(reserva.Avaliacao));
			ModelState.Remove(nameof(reserva.Entrega));
			ModelState.Remove(nameof(reserva.Levantamento));
			ModelState.Remove(nameof(reserva.ApplicationUser));
			ModelState.Remove(nameof(reserva.ApplicationUserId));

			reserva.Concluido = false;
			reserva.Estado = StatusReserva.pending;
			var user = await _userManager.GetUserAsync(User);
			if (user == null)
			{
				ModelState.AddModelError("", "Nao tem user logado");
				return View(reserva);
			}
			reserva.ApplicationUser = user;
			reserva.ApplicationUserId = user.Id;
			reserva.DataReserva = DateTime.Today;

			if (ModelState.IsValid)
			{
				_context.Add(reserva);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", reserva.ApplicationUserId);
			ViewData["VeiculoId"] = new SelectList(_context.Veiculos, "Id", "Id", reserva.VeiculoId);
			ViewBag.veiculo = veiculo;
			return View(reserva);
		}

		// GET: Reservas/Edit/5
		[Authorize(Roles = "Gestor,Funcionario")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Reservas == null)
			{
				return NotFound();
			}

			var reserva = await _context.Reservas.FindAsync(id);
			if (reserva == null)
			{
				return NotFound();
			}
			ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", reserva.ApplicationUserId);
			ViewData["VeiculoId"] = new SelectList(_context.Veiculos, "Id", "Id", reserva.VeiculoId);
			return View(reserva);
		}

		// POST: Reservas/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Gestor,Funcionario")]
		public async Task<IActionResult> Edit(int id, [Bind("ReservaId,Concluido,VeiculoId,ApplicationUserId")] Reserva reserva)
		{
			if (id != reserva.ReservaId)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(reserva);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ReservaExists(reserva.ReservaId))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}

Views/Registos/Create.cshtml
@using Rental4You.Models
@model Rental4You.Models.Registo

@{
    ViewData["Title"] = "Create";
}

@if(Model.Tipo == RegistoType.LEVANTAMENTO){
    <h4>Levantamento</h4>
}else{
    <h4>Entrega</h4>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReservaId"/>
            <input type="hidden" id="type" asp-for="Tipo"/>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kms" class="control-label"></label>
                <input asp-for="Kms" class="form-control" />
                <span asp-validation-for="Kms" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input id="danos" class="form-check-input" asp-for="Danos" /> @Html.DisplayNameFor(model => model.Danos)
                </label>
            </div>
            
            <div id="ImagesInput" style=" display: none;" class="col-md-8">
                <p>Adicionar Imagens</p>
                <div class="col-4" id="ImagesColumns">
                    <div class="">
                       <img id="NovaIMG" class="img-thumbnail" src="" />
                    </div>
                </div>
            
                <div class="form-group">
                    <input type="file" name="ficheiros" id="ficheiros" multiple
                           accept=".png,.jpg,image/png,image/jpeg"
                           class="form-control"
                           style="border: 0px!important; padding: 0p;padding-top: 10px; padding-bottom: 30px;"
                           onchange="updateImages(this.files)" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Observacoes" class="control-label"></label>
                <textarea asp-for="Observacoes" class="form-control" ></textarea>
                <span asp-validation-for="Observacoes" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary btn-sm" />
                <a asp-action="Index" asp-controller="Reservas" class="btn btn-secondary btn-sm">Voltar a Lista</a>
            </div>
        </form>
    </div>
    <div class="col-4" id="ImagesUpdated">
        <div class="">
            <img id="NovaIMG" class="img-thumbnail" src="" />
        </div>
    </div>
    <div class="col-4" id="ImagesColumns">
        <div class="">
                <img id="NovaIMG" class="img-thumbnail" src="" />
        </div>
    </div>
    
        
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        var checkbox = document.getElementById("danos");
        var type = document.getElementById("type");
        
        var imageInput = document.getElementById("ImagesInput");
        checkbox.addEventListener('change', function() {
            
            if("@Model.Tipo" ==  "@RegistoType.ENTREGA.ToString()"){
                if (this.checked) {
                    imageInput.style="display: block;"
                } else {
                    imageInput.style="display: none;"
                    imageInput.value="";
                }
            }
            
        });

        function updateImages(img){
            console.log(img)
            
            deleteChild()
            let i = 0;
            while(i < img.length){
                let url = window.URL.createObjectURL(img[i]);    
                console.log(url)
                let div = document.createElement("div");
                div.classList.add("image_input");
                let image = document.createElement("img");
                image.style="max-width:240px;max-height:120px;"
                image.src = url;
                div.appendChild(image);
                let imgsDiv = document.getElementById('ImagesColumns');
                imgsDiv.appendChild(div);  
                i++;
            }
        }

        function deleteChild() {
            
            let imgsDiv = document.getElementById('ImagesColumns');
            var child = imgsDiv.lastElementChild; 
            while (child) {
                imgsDiv.removeChild(child);
                child = imgsDiv.lastElementChild;
            }
        }
    


    </script>
}

Views/Registos/Delete.cshtml
@model Rental4You.Models.Registo

@{
    ViewData["Title"] = "Delete";
}

<h1>Remover</h1>

<h3>Tem a certeza que quer remover este registo?</h3>
<div>
    <h4>Registo</h4>
    <hr />
    <div class="row">
        <div class="col-5">
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Data)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Data)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Kms)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Kms)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Danos)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Danos)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Observacoes)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Observacoes)
                </dd>
            </dl>
            
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Remover" class="btn btn-danger btn-sm" /> |
                <a asp-action="Index" asp-controller="Reservas" class="btn btn-secondary btn-sm">Voltar a Lista</a>
            </form>
        </div>
        <div class="col-7">
                @if(ViewBag.NFich > 0)
                {
                    @foreach(var file in ViewBag.Ficheiros)
                    {
                        <div class="row " style="border-radius:10px; border:1px dotted #ccc;">
                            <a asp-action="deleteImage" asp-route-id="@Model.Id" asp-route-image="@file">
                                <svg bootstrap-icon="XCircleFill" onclick="return confirm("Tem a certeza que deseja apagar esta foto")"
                                     class="text-danger" width="24px;" height="24px" arial-label="Trash"></svg>

                            </a>
                            <img src="@file" class="img-thumbnail" style="max-width:150px; max-height:150px;"/>
                        </div>
                    }



                }
                else
                {
                    <p class="alert text-danger alert-warning"> Ainda não tem imagens associadas</p>
                }

        </div>
    </div>
</div>

Views/Registos/Details.cshtml
@model Rental4You.Models.Registo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Registo</h4>
    <hr />
    <div class="row">
        <div class="col-5">
            <dl class="row">
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Data)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Data)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Funcionario)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Funcionario.PrimeiroNome) @Html.DisplayFor(model => model.Funcionario.UltimoNome)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Kms)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Kms)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Danos)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Danos)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Observacoes)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Observacoes)
                </dd>
            </dl>
        </div>
    
        <div class="col-7">
                @if(ViewBag.NFich > 0)
                {
                    @foreach(var file in ViewBag.Ficheiros)
                    {
                        <div class="row " >
                            <img src="@file" class="img-thumbnail" style="max-width:150px; max-height:150px;border-radius:10px; border:1px dotted #ccc;"/>
                        </div>
                    }
                }
                else
                {
                    <p class="alert text-danger alert-warning"> Ainda não tem imagens associadas</p>
                }

        </div>
    </div>
</div>
<div>
    @*<a asp-action="Edit" class="btn btn-warning btn-sm" asp-route-id="@Model?.Id">Editar</a>*@
    <a asp-action="Index" asp-controller="Reservas" class="btn btn-secondary btn-sm">Voltar a Lista</a>
</div>

Views/Registos/Edit.cshtml
@model Rental4You.Models.Registo

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Registo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kms" class="control-label"></label>
                <input asp-for="Kms" class="form-control" />
                <span asp-validation-for="Kms" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Danos" /> @Html.DisplayNameFor(model => model.Danos)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Observacoes" class="control-label"></label>
                <input asp-for="Observacoes" class="form-control" />
                <span asp-validation-for="Observacoes" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary btn-sm" />
                <a asp-action="Index" asp-controller="Reservas" class="btn btn-secondary btn-sm">Voltar a Lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}